package com.publiccar.code.model;
// default package
// Generated 2018-5-23 12:46:47 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsumptionId generated by hbm2java
 */
@Embeddable
public class ConsumptionId implements java.io.Serializable {

	private Integer consumptionId;
	private Integer carId;
	private Integer deiverId;
	private String consumptionAddress;
	private String consumptionDate;
	private String consumptionMoney;
	private Integer consumptionNumber;

	public ConsumptionId() {
	}

	public ConsumptionId(Integer consumptionId, Integer carId, Integer deiverId, String consumptionAddress,
			String consumptionDate, String consumptionMoney, Integer consumptionNumber) {
		this.consumptionId = consumptionId;
		this.carId = carId;
		this.deiverId = deiverId;
		this.consumptionAddress = consumptionAddress;
		this.consumptionDate = consumptionDate;
		this.consumptionMoney = consumptionMoney;
		this.consumptionNumber = consumptionNumber;
	}

	@Column(name = "consumption_id")
	public Integer getConsumptionId() {
		return this.consumptionId;
	}

	public void setConsumptionId(Integer consumptionId) {
		this.consumptionId = consumptionId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "deiver_id")
	public Integer getDeiverId() {
		return this.deiverId;
	}

	public void setDeiverId(Integer deiverId) {
		this.deiverId = deiverId;
	}

	@Column(name = "consumption_address")
	public String getConsumptionAddress() {
		return this.consumptionAddress;
	}

	public void setConsumptionAddress(String consumptionAddress) {
		this.consumptionAddress = consumptionAddress;
	}

	@Column(name = "consumption_date", length = 0)
	public String getConsumptionDate() {
		return this.consumptionDate;
	}

	public void setConsumptionDate(String consumptionDate) {
		this.consumptionDate = consumptionDate;
	}

	@Column(name = "consumption_money")
	public String getConsumptionMoney() {
		return this.consumptionMoney;
	}

	public void setConsumptionMoney(String consumptionMoney) {
		this.consumptionMoney = consumptionMoney;
	}

	@Column(name = "consumption_number")
	public Integer getConsumptionNumber() {
		return this.consumptionNumber;
	}

	public void setConsumptionNumber(Integer consumptionNumber) {
		this.consumptionNumber = consumptionNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConsumptionId))
			return false;
		ConsumptionId castOther = (ConsumptionId) other;

		return ((this.getConsumptionId() == castOther.getConsumptionId())
				|| (this.getConsumptionId() != null && castOther.getConsumptionId() != null
						&& this.getConsumptionId().equals(castOther.getConsumptionId())))
				&& ((this.getCarId() == castOther.getCarId()) || (this.getCarId() != null
						&& castOther.getCarId() != null && this.getCarId().equals(castOther.getCarId())))
				&& ((this.getDeiverId() == castOther.getDeiverId()) || (this.getDeiverId() != null
						&& castOther.getDeiverId() != null && this.getDeiverId().equals(castOther.getDeiverId())))
				&& ((this.getConsumptionAddress() == castOther.getConsumptionAddress())
						|| (this.getConsumptionAddress() != null && castOther.getConsumptionAddress() != null
								&& this.getConsumptionAddress().equals(castOther.getConsumptionAddress())))
				&& ((this.getConsumptionDate() == castOther.getConsumptionDate())
						|| (this.getConsumptionDate() != null && castOther.getConsumptionDate() != null
								&& this.getConsumptionDate().equals(castOther.getConsumptionDate())))
				&& ((this.getConsumptionMoney() == castOther.getConsumptionMoney())
						|| (this.getConsumptionMoney() != null && castOther.getConsumptionMoney() != null
								&& this.getConsumptionMoney().equals(castOther.getConsumptionMoney())))
				&& ((this.getConsumptionNumber() == castOther.getConsumptionNumber())
						|| (this.getConsumptionNumber() != null && castOther.getConsumptionNumber() != null
								&& this.getConsumptionNumber().equals(castOther.getConsumptionNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getConsumptionId() == null ? 0 : this.getConsumptionId().hashCode());
		result = 37 * result + (getCarId() == null ? 0 : this.getCarId().hashCode());
		result = 37 * result + (getDeiverId() == null ? 0 : this.getDeiverId().hashCode());
		result = 37 * result + (getConsumptionAddress() == null ? 0 : this.getConsumptionAddress().hashCode());
		result = 37 * result + (getConsumptionDate() == null ? 0 : this.getConsumptionDate().hashCode());
		result = 37 * result + (getConsumptionMoney() == null ? 0 : this.getConsumptionMoney().hashCode());
		result = 37 * result + (getConsumptionNumber() == null ? 0 : this.getConsumptionNumber().hashCode());
		return result;
	}

}
