package com.publiccar.code.model;
// default package
// Generated 2018-5-23 12:46:47 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Consumption generated by hbm2java
 */
@Entity
@Table(name = "consumption", catalog = "publiccar")
public class Consumption implements java.io.Serializable {

	private ConsumptionId id;

	public Consumption() {
	}

	public Consumption(ConsumptionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "consumptionId", column = @Column(name = "consumption_id")),
			@AttributeOverride(name = "carId", column = @Column(name = "car_id")),
			@AttributeOverride(name = "deiverId", column = @Column(name = "deiver_id")),
			@AttributeOverride(name = "consumptionAddress", column = @Column(name = "consumption_address")),
			@AttributeOverride(name = "consumptionDate", column = @Column(name = "consumption_date", length = 0)),
			@AttributeOverride(name = "consumptionMoney", column = @Column(name = "consumption_money")),
			@AttributeOverride(name = "consumptionNumber", column = @Column(name = "consumption_number")) })
	public ConsumptionId getId() {
		return this.id;
	}

	public void setId(ConsumptionId id) {
		this.id = id;
	}

}
