package com.publiccar.code.model;
// default package
// Generated 2018-5-23 12:46:47 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DempId generated by hbm2java
 */
@Embeddable
public class DempId implements java.io.Serializable {

	private Integer dempId;
	private String dempName;

	public DempId() {
	}

	public DempId(Integer dempId, String dempName) {
		this.dempId = dempId;
		this.dempName = dempName;
	}

	@Column(name = "demp_id")
	public Integer getDempId() {
		return this.dempId;
	}

	public void setDempId(Integer dempId) {
		this.dempId = dempId;
	}

	@Column(name = "demp_name")
	public String getDempName() {
		return this.dempName;
	}

	public void setDempName(String dempName) {
		this.dempName = dempName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DempId))
			return false;
		DempId castOther = (DempId) other;

		return ((this.getDempId() == castOther.getDempId()) || (this.getDempId() != null
				&& castOther.getDempId() != null && this.getDempId().equals(castOther.getDempId())))
				&& ((this.getDempName() == castOther.getDempName()) || (this.getDempName() != null
						&& castOther.getDempName() != null && this.getDempName().equals(castOther.getDempName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDempId() == null ? 0 : this.getDempId().hashCode());
		result = 37 * result + (getDempName() == null ? 0 : this.getDempName().hashCode());
		return result;
	}

}
