package com.publiccar.code.model;
// default package
// Generated 2018-5-23 12:46:47 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Demp generated by hbm2java
 */
@Entity
@Table(name = "demp", catalog = "publiccar")
public class Demp implements java.io.Serializable {

	private DempId id;

	public Demp() {
	}

	public Demp(DempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dempId", column = @Column(name = "demp_id")),
			@AttributeOverride(name = "dempName", column = @Column(name = "demp_name")) })
	public DempId getId() {
		return this.id;
	}

	public void setId(DempId id) {
		this.id = id;
	}

}
