package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Income generated by hbm2java
 */
@Entity
@Table(name = "income", catalog = "publiccar")
public class Income implements java.io.Serializable {

	private Integer incomeId;
	private Integer carId;
	private String incomeContent;
	private Date incomeDate;

	public Income() {
	}

	public Income(Integer carId, String incomeContent, Date incomeDate) {
		this.carId = carId;
		this.incomeContent = incomeContent;
		this.incomeDate = incomeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "income_id", unique = true, nullable = false)
	public Integer getIncomeId() {
		return this.incomeId;
	}

	public void setIncomeId(Integer incomeId) {
		this.incomeId = incomeId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "income_content", length = 100)
	public String getIncomeContent() {
		return this.incomeContent;
	}

	public void setIncomeContent(String incomeContent) {
		this.incomeContent = incomeContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "income_date", length = 10)
	public Date getIncomeDate() {
		return this.incomeDate;
	}

	public void setIncomeDate(Date incomeDate) {
		this.incomeDate = incomeDate;
	}

}
