package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Insurance generated by hbm2java
 */
@Entity
@Table(name = "insurance", catalog = "publiccar")
public class Insurance implements java.io.Serializable {

	private Integer insuranceId;
	private Integer carId;
	private String insuranceContent;
	private Date insuranceDate;

	public Insurance() {
	}

	public Insurance(Integer carId, String insuranceContent, Date insuranceDate) {
		this.carId = carId;
		this.insuranceContent = insuranceContent;
		this.insuranceDate = insuranceDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "insurance_id", unique = true, nullable = false)
	public Integer getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(Integer insuranceId) {
		this.insuranceId = insuranceId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "insurance_content", length = 100)
	public String getInsuranceContent() {
		return this.insuranceContent;
	}

	public void setInsuranceContent(String insuranceContent) {
		this.insuranceContent = insuranceContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "insurance_date", length = 10)
	public Date getInsuranceDate() {
		return this.insuranceDate;
	}

	public void setInsuranceDate(Date insuranceDate) {
		this.insuranceDate = insuranceDate;
	}

}
