package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Peccancy generated by hbm2java
 */
@Entity
@Table(name = "peccancy", catalog = "publiccar")
public class Peccancy implements java.io.Serializable {

	private Integer peccancyId;
	private Integer carId;
	private String peccancyContent;
	private Date peccancyDate;

	public Peccancy() {
	}

	public Peccancy(Integer carId, String peccancyContent, Date peccancyDate) {
		this.carId = carId;
		this.peccancyContent = peccancyContent;
		this.peccancyDate = peccancyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peccancy_id", unique = true, nullable = false)
	public Integer getPeccancyId() {
		return this.peccancyId;
	}

	public void setPeccancyId(Integer peccancyId) {
		this.peccancyId = peccancyId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "peccancy_content", length = 100)
	public String getPeccancyContent() {
		return this.peccancyContent;
	}

	public void setPeccancyContent(String peccancyContent) {
		this.peccancyContent = peccancyContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "peccancy_date", length = 10)
	public Date getPeccancyDate() {
		return this.peccancyDate;
	}

	public void setPeccancyDate(Date peccancyDate) {
		this.peccancyDate = peccancyDate;
	}

}
