package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PublicCar generated by hbm2java
 */
@Entity
@Table(name = "public_car", catalog = "publiccar")
public class PublicCar implements java.io.Serializable {

	private Integer carId;
	private String carPlate;
	private String carModel;
	private Integer driver;

	public PublicCar() {
	}

	public PublicCar(String carPlate, String carModel, Integer driver) {
		this.carPlate = carPlate;
		this.carModel = carModel;
		this.driver = driver;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "car_plate", length = 50)
	public String getCarPlate() {
		return this.carPlate;
	}

	public void setCarPlate(String carPlate) {
		this.carPlate = carPlate;
	}

	@Column(name = "car_model", length = 100)
	public String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	@Column(name = "driver")
	public Integer getDriver() {
		return this.driver;
	}

	public void setDriver(Integer driver) {
		this.driver = driver;
	}

}
