package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "publiccar")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPassword;
	private String userIdentity;
	private Double userAge;

	public User() {
	}

	public User(String userName, String userPassword, String userIdentity, Double userAge) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userIdentity = userIdentity;
		this.userAge = userAge;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_password", length = 100)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_identity", length = 11)
	public String getUserIdentity() {
		return this.userIdentity;
	}

	public void setUserIdentity(String userIdentity) {
		this.userIdentity = userIdentity;
	}

	@Column(name = "user_age", precision = 22, scale = 0)
	public Double getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Double userAge) {
		this.userAge = userAge;
	}

}
