package com.publiccar.code.model;
// default package
// Generated 2018-5-19 23:06:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wear generated by hbm2java
 */
@Entity
@Table(name = "wear", catalog = "publiccar")
public class Wear implements java.io.Serializable {

	private Integer wearId;
	private Integer carId;
	private String wearContent;
	private Date wearDate;

	public Wear() {
	}

	public Wear(Integer carId, String wearContent, Date wearDate) {
		this.carId = carId;
		this.wearContent = wearContent;
		this.wearDate = wearDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wear_id", unique = true, nullable = false)
	public Integer getWearId() {
		return this.wearId;
	}

	public void setWearId(Integer wearId) {
		this.wearId = wearId;
	}

	@Column(name = "car_id")
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "wear_content", length = 100)
	public String getWearContent() {
		return this.wearContent;
	}

	public void setWearContent(String wearContent) {
		this.wearContent = wearContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "wear_date", length = 10)
	public Date getWearDate() {
		return this.wearDate;
	}

	public void setWearDate(Date wearDate) {
		this.wearDate = wearDate;
	}

}
